services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:80" # Maps port 3000 on your machine to port 80 in the Nginx container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Exposes your Java API on port 8080